package sim.pipeline.wave;

/**
 * It represents a vibration causing an effect E.
 * @param <E> An effect generated by this vibration.
 */
public interface Vibration<E> {

    // Generating the targeted effect
    default void happen(E effect){
        //System.out.println("Generate an effect : " + effect);
    }
}
